"""add portal_url to agent_tasks

Revision ID: 52470bb3ef1e
Revises: f2a4c8e91b3d
Create Date: 2026-06-17 11:21:03.331746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52470bb3ef1e'
down_revision: Union[str, Sequence[str], None] = 'f2a4c8e91b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_tasks', sa.Column('portal_url', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_tasks', 'portal_url')
    # ### end Alembic commands ###
