"""add runner_tokens table

Revision ID: 8831df458bec
Revises: e9f3a1b8c2d7
Create Date: 2026-06-28 11:26:57.692148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8831df458bec'
down_revision: Union[str, Sequence[str], None] = 'e9f3a1b8c2d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runner_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runner_tokens_user_email'), 'runner_tokens', ['user_email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runner_tokens_user_email'), table_name='runner_tokens')
    op.drop_table('runner_tokens')
    # ### end Alembic commands ###
