"""add evidence_files table

Revision ID: f71a8f5f6c90
Revises: 8c23574c59c3
Create Date: 2026-06-18 11:26:43.869645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f71a8f5f6c90'
down_revision: Union[str, Sequence[str], None] = '8c23574c59c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('subtask', sa.String(length=1000), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Backfill: every pre-existing Evidence row had exactly one file on the
    # row itself — give it a matching evidence_files entry so old rows render
    # the same way as new multi-file rows.
    op.execute(
        """
        INSERT INTO evidence_files (evidence_id, file_name, file_url, sort_order, created_at)
        SELECT id, file_name, file_url, 0, created_at FROM evidence
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence_files')
    # ### end Alembic commands ###
